info:
  version: 1.0.1
  description: BSF initial local configuration

configuration:
  bsfName: BSF
  sbi:
    scheme: http
    registerIPv4: bsf.free5gc.org # Matches docker-compose service name/alias
    bindingIPv4: 0.0.0.0
    port: 8000
  nrfUri: http://nrf.free5gc.org:8000
  serviceNameList:
    - nbsf-management

logger:
  BSF:
    debugLevel: info
    ReportCaller: false
