mcc: "208" # Mobile Country Code value
mnc: "93" # Mobile Network Code value (2 or 3 digits)

nci: "0x000000010" # NR Cell Identity (36-bit)
idLength: 32 # NR gNB ID length in bits [22...32]
tac: 1 # Tracking Area Code

linkIp: 172.18.1.30 # gNB N2 IP (Simulated link)
ngapIp: 172.18.1.30 # gNB N2 IP
gtpIp: 172.18.2.30 # gNB N3 IP

# List of AMF address information
amfConfigs:
  - address: 172.18.1.10 # AMF N2 IP
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 0x1
    sd: 0x010203
  - sst: 0x1
    sd: 0x112233

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
